spring:
  application:
    name: the-libs

  datasource:
    url: jdbc:postgresql://localhost:5431/postgres
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  graphql:
    path: /graphql # endpoint principal da API GraphQL

  graphiql:
    enabled: true # ativa a interface web
    endpoint: /graphql
    path: /graph
